#!/usr/bin/env node
/**
 * Points .env.local at the local Supabase stack so the app runs with no cloud
 * accounts at all.
 *
 *   npm run supabase:start   # first run pulls Docker images (a few minutes)
 *   npm run supabase:reset   # migrations + local seed
 *   npm run local:env        # writes .env.local from `supabase status`
 *
 * Keys this script owns (Supabase URL/keys, APP_URL, CRON_SECRET) are replaced.
 * Every other value already in .env.local is kept, so a real NVIDIA_API_KEY or
 * RESEND_API_KEY survives a re-run.
 */
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const ENV_PATH = ".env.local";
const IS_WINDOWS = process.platform === "win32";

function run(bin, args) {
  return spawnSync(bin, args, {
    encoding: "utf8",
    shell: IS_WINDOWS, // resolves supabase.cmd / npx.cmd on Windows
  });
}

/** `supabase status -o env`, falling back to `npx supabase` when not on PATH. */
function supabaseStatus() {
  const direct = run("supabase", ["status", "-o", "env"]);
  if (!direct.error && direct.status === 0) return direct;

  const viaNpx = run("npx", ["--yes", "supabase", "status", "-o", "env"]);
  if (!viaNpx.error && viaNpx.status === 0) return viaNpx;

  return direct.error ? viaNpx : direct;
}

function parseEnv(text) {
  const map = new Map();
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    map.set(line.slice(0, eq).trim(), line.slice(eq + 1).trim());
  }
  return map;
}

const status = supabaseStatus();
if (status.status !== 0 && status.status !== null) {
  const detail = (status.stderr || status.stdout || "").trim();
  console.error("Could not read the local Supabase stack.\n");
  if (detail) console.error(`${detail}\n`);
  console.error(
    "Start it first, then run this again:\n  npm run supabase:start\n",
  );
  process.exit(1);
}

const vars = parseEnv(status.stdout ?? "");
const apiUrl = vars.API_URL;
const anonKey = vars.ANON_KEY || vars.PUBLISHABLE_KEY;
const serviceKey = vars.SERVICE_ROLE_KEY || vars.SECRET_KEY;

if (!apiUrl || !anonKey || !serviceKey) {
  console.error(
    "The stack is up, but `supabase status -o env` did not include the API URL and keys.",
  );
  console.error(`Saw: ${Object.keys(vars).join(", ") || "nothing"}`);
  process.exit(1);
}

const entries = existsSync(ENV_PATH)
  ? parseEnv(readFileSync(ENV_PATH, "utf8"))
  : new Map();

const local = {
  NEXT_PUBLIC_SUPABASE_URL: apiUrl,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: anonKey,
  SUPABASE_SERVICE_ROLE_KEY: serviceKey,
  APP_URL: "http://localhost:3000",
  CRON_SECRET: entries.get("CRON_SECRET") || randomBytes(24).toString("hex"),
};

for (const [key, value] of Object.entries(local)) entries.set(key, value);

// Documented defaults for anything still missing (NVIDIA_MODEL, DIGEST_FROM…).
for (const [key, value] of parseEnv(readFileSync(".env.example", "utf8"))) {
  if (!entries.has(key)) entries.set(key, value);
}

const body = [...entries.entries()]
  .map(([key, value]) => `${key}=${value}`)
  .join("\n");

writeFileSync(
  ENV_PATH,
  [
    "# Local development — generated by `npm run local:env`.",
    "# Points at the Supabase stack running in Docker. Gitignored.",
    "",
    body,
    "",
  ].join("\n"),
  "utf8",
);

console.log(`Wrote ${ENV_PATH} for ${apiUrl}`);
console.log("NEXT_PUBLIC_SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY set.");
if (!entries.get("NVIDIA_API_KEY")) {
  console.log(
    "No NVIDIA_API_KEY: triage will use the built-in rule-based fallback.",
  );
}
console.log("\nNext:\n  npm run dev   →  http://localhost:3000");
console.log("Sign in with admin@local.test; read the link at http://127.0.0.1:54324");
